#!/usr/bin/env python3
"""Генерирует C-файл с бинарным blob assets.tar (fallback для платформ без ld -b binary)."""

from __future__ import annotations

import sys
from pathlib import Path


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("usage: build_assets_blob_c.py <assets.tar> <out.c>", file=sys.stderr)
        return 2

    src = Path(argv[1]).resolve()
    out = Path(argv[2]).resolve()

    if not src.exists() or not src.is_file():
        print(f"input tar not found: {src}", file=sys.stderr)
        return 1

    data = src.read_bytes()

    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as fh:
        fh.write("/* generated by tools/build_assets_blob_c.py */\n")
        fh.write("#include <stddef.h>\n\n")
        fh.write("const unsigned char astra_assets_tar[] = {\n")
        for i in range(0, len(data), 12):
            chunk = data[i : i + 12]
            hexes = ", ".join(f"0x{b:02x}" for b in chunk)
            fh.write(f"    {hexes},\n")
        fh.write("};\n")
        fh.write(f"const unsigned int astra_assets_tar_len = {len(data)}u;\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
