#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Генерирует C-файл с бинарным blob assets.tar (fallback для платформ без ld -b binary).

Совместим с Python 2.7 и Python 3.x.
"""

from __future__ import print_function

import io
import os
import sys


def _bytes_iter(data):
    # Python2: bytes -> str, iteration yields 1-char strings.
    # Python3: bytes -> bytes, iteration yields ints.
    for b in data:
        if isinstance(b, int):
            yield b
        else:
            yield ord(b)


def main(argv):
    if len(argv) != 3:
        print("usage: build_assets_blob_c.py <assets.tar> <out.c>", file=sys.stderr)
        return 2

    src = os.path.abspath(argv[1])
    out = os.path.abspath(argv[2])

    if not os.path.isfile(src):
        print("input tar not found: {}".format(src), file=sys.stderr)
        return 1

    with open(src, "rb") as fh:
        data = fh.read()

    out_dir = os.path.dirname(out)
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir)

    with io.open(out, "w", encoding="utf-8") as fh:
        fh.write("/* generated by tools/build_assets_blob_c.py */\n")
        fh.write("#include <stddef.h>\n\n")
        fh.write("const unsigned char astra_assets_tar[] = {\n")

        buf = list(_bytes_iter(data))
        for i in range(0, len(buf), 12):
            chunk = buf[i : i + 12]
            hexes = ", ".join("0x{:02x}".format(b) for b in chunk)
            fh.write("    {},\n".format(hexes))

        fh.write("};\n")
        fh.write("const unsigned int astra_assets_tar_len = {}u;\n".format(len(buf)))

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
